baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: Environmental Computing
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: yes
params:
  author: Fonti Kar, Dan Falster, and Will Cornwell
  customMermaidURL: NA
  description: Environmental Computing
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/nicercode/EnvironmentalComputing/edit/develop/content/
  showVisitedLinks: yes
  titleSeparator: '::'
  themeVariant: 'green'
outputs:
  home:
    - HTML
    - RSS
    - JSON

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

markup:
  goldmark:
    renderer:
      unsafe: true
