baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: Environmental Computing
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: yes
params:
  author: Mathieu Cornic
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: Documentation for Hugo Learn Theme
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/
  showVisitedLinks: yes
  titleSeparator: '::'
  themeVariant: 'green'
outputs:
  home:
    - HTML
    - RSS
    - JSON



markup:
  goldmark:
    renderer:
      unsafe: true
