---
weight: 1
title: "Single Factor ANOVA"
output: html_document
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>Analysis of variance (ANOVA) is one of the most frequently used techniques in the biological and environmental sciences. ANOVA is used to contrast a continuous dependent variable <em>y</em> across levels of one or more categorical independent variables <em>x</em>. The independent variables are termed the factor or treatment, and the various categories within that treatment are termed the levels. In this module, we will start with the simplest design - those with a single factor.</p>
<p>Where an independent samples <em>t</em>-test would be used for comparison of group means across two levels, ANOVA is used for the comparison of &gt;2 group means, or when there are more than two or more predictor variables (see <a href="/../analysis-of-variance-factorial/">ANOVA: factorial</a>). The logic of this test is essentially the same as the <em>t</em>-test - it compares variation between groups to variation within groups to determine whether the observed differences are due to chance or not.</p>
<p><img src="ANOVA_single_factor_image.png" /></p>
<p>For example, to contrast the the hatching times of turtle eggs incubated at four different temperatures (15°C, 20°C, 25°C and 30°C), hatching time is the continuous response variable and temperature is the categorical predictor variable with with four levels. The null hypothesis would be that mean hatching time is equal for all temperatures (H<sub>o</sub>: <span class="math inline">\(\mu_{15} = \mu_{20} = \mu_{25} = \mu_{30}\)</span>).</p>
<p>Note that an ANOVA is a linear model, just like linear regression except that the predictor variables are categorical rather than continuous.</p>
<p><span class="math display">\[y_{ij} = \mu + \alpha_i + \varepsilon_{ij}\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the overall mean and <span class="math inline">\(\alpha_i\)</span> is the effect of the i<sup>th</sup> group.</p>
<p>It is the same as a multiple linear regression with a predictor variable for each level of the categorical variable (each coded as a dummy variable). For the question of whether hatching time of turtles differs between four incubation tempeatures, we must fit four parameters to describe the mean response of each temperature (rather than just a single intercept and single slope in a simple linear regression). For this example, our linear model equation will have this form:</p>
<p><span class="math display">\[HatchingTime = \mu + \beta_1.Temp_{15} + \beta_2.Temp_{20} + \beta_3.Temp_{25} + \beta_4.Temp_{30} + \varepsilon\]</span></p>
<p>ANOVA partitions the total variance into a component that can be explained by the predictor variable (among levels of the treatment), and a component that cannot be explained (within levels, the residual variance). The test statistic, <em>F</em>, is the ratio of these two sources of variation.</p>
<p><span class="math display">\[F = \frac{MS_{among}}{MS_{within}}\]</span></p>
<p>where <em>MS</em> are the mean squares, a measure of variation. The probability of obtaining the observed value of <em>F</em> is calculated from the known probability distribution of <em>F</em>, with two degrees of freedom (one for the numerator = the number of levels -1) and one for the denominator (number of replicates per level - 1 x number of levels).</p>
<div id="running-the-analysis" class="section level3">
<h3>Running the analysis</h3>
<p>The data should be formatted such that the individual replicates are rows and the variables are separate columns. Include a column for the dependent variable, <em>y</em>, and a corresponding column for the categorical variable, <em>x</em>. Download the sample data set for the turtle hatching example, <a href="/datasets/Turtles.csv">Turtles.csv</a>, import into R and check that temperature variable is a factor with the <code>str</code> function.</p>
<pre class="r"><code>Turtles = read.csv(file = &quot;Turtles.csv&quot;,header=TRUE)
str(Turtles)</code></pre>
<p>In this case, because we have numbers for the four levels of the Temperature treatment, we need to change that variable to become a factor rather than an integer.</p>
<pre class="r"><code>Turtles$Temperature = factor(Turtles$Temperature)</code></pre>
<p>Now, we can run the analysis of variance contrasting hatching time (days) across temperatures using the function <code>aov</code>. The arguments of the function are simply a formula statement, <code>y~x</code>, with the response variable to the left of the ~, the predictor variable to the right, and some code to specify which data frame holds those variables.</p>
<pre class="r"><code>Turtles.aov = aov(Days ~ Temperature, data = Turtles)</code></pre>
<p>The output from this analysis can be seen by using the <code>summary</code> function on the object created.</p>
<pre class="r"><code>summary(Turtles.aov)</code></pre>
<p>Exactly the same analysis can be reproduced using the linear model function <code>lm</code>.</p>
<pre class="r"><code>Turtles.lm = lm(Days ~ Temperature,data=Turtles)
summary(Turtles.lm)</code></pre>
</div>
<div id="interpreting-the-results" class="section level3">
<h3>Interpreting the results</h3>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Temperature  3   8025  2675.2   15.98 9.08e-07 ***
## Residuals   36   6027   167.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The summary output of an ANOVA object is a table with the degrees of freedom (Df), sums of squares (Sum Sq), mean squares (Mean Sq) for the predictor variable (i.e., variation among levels of your treatment) and for the Residuals (i.e., varation within the levels). The test statistic, <em>F</em> value and its associated <em>p</em>-value (Pr(&gt;F)) are also presented.</p>
<p>First check the degrees of freedom. The factor Df = the number of levels of your factor - 1. The residual Df = <em>a(n-1)</em>, where <em>a</em> = the number of levels of your factor and <em>n</em> = sample size (replicates per level).</p>
<p>The sums of squares and mean squares are measures of variation. The <em>F</em> statistic is the ratio of <em>MS<sub>among</sub></em> and <em>MS<sub>within</sub></em> and the <em>p</em>-value is the probability of the observed <em>F</em> value from the <em>F</em> distribution (with the given degrees of freedom).</p>
<p>The main thing to look at in the ANOVA table is whether your predictor variable had a significant effect on your response variable. In this example, the probability that all four incubation temperatures are equal is &lt;0.001. This is very unlikely and much less than 0.05. We would conclude that there is a difference in hatching times between the temperatures. We are also interested in the R^2 value which tells us how much variation was explained by the model.</p>
<p>If you use the <code>lm</code> function, you get a bit more information from the summary of the linear model output.</p>
<pre><code>## 
## Call:
## lm(formula = Days ~ Temperature, data = Turtles)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.200  -9.225   1.650   9.025  19.400 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     58.400      4.092  14.273  &lt; 2e-16 ***
## Temperature20  -13.800      5.787  -2.385   0.0225 *  
## Temperature25   -9.200      5.787  -1.590   0.1206    
## Temperature30  -38.300      5.787  -6.619 1.04e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.94 on 36 degrees of freedom
## Multiple R-squared:  0.5711, Adjusted R-squared:  0.5354 
## F-statistic: 15.98 on 3 and 36 DF,  p-value: 9.082e-07</code></pre>
<p>The output for the standard ANOVA table is down the bottom and above it you get the actual parameter estimates from the linear model (the <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span> etc from above). In this example, turtles at 15°C hatched after 58.4 days, on average (the intercept in the model). The other parameter estimates are differences between each level of temperature and the intercept. For example, at 20°C they were 13.8 days faster (i.e., the mean for 20°C = 58.4-13.8 = 44.6 days).</p>
<p>If you detect any significant differences in the ANOVA, we are then interested in knowing exactly which groups differ from one another, and which do not. Remember that a significant <em>p</em> value in the test you just ran would reject the null hypothesis the means of the dependent variable were the same across all groups, but not identify which were different from each other. To see a comparison between each mean and each other mean, we can use a Tukey’s post-hoc test.</p>
<pre class="r"><code>TukeyHSD(Turtles.aov)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Days ~ Temperature, data = Turtles)
## 
## $Temperature
##        diff       lwr        upr     p adj
## 20-15 -13.8 -29.38469   1.784689 0.0982694
## 25-15  -9.2 -24.78469   6.384689 0.3969971
## 30-15 -38.3 -53.88469 -22.715311 0.0000006
## 25-20   4.6 -10.98469  20.184689 0.8562615
## 30-20 -24.5 -40.08469  -8.915311 0.0008384
## 30-25 -29.1 -44.68469 -13.515311 0.0000785</code></pre>
</div>
<div id="assumptions-to-check" class="section level3">
<h3>Assumptions to check</h3>
<p>The important assumptions of ANOVA are independence, homegeneity of variance and normality. We advocate a qualitative evalutation of the normality and homogeneity of variance assumptions, by examining the patterns of variation in the residuals, rather than a formal test such has Cochran’s test. Linear models in general are quite ‘robust’ for violating these assumptions (heterogeneity and normality), within reason.</p>
<p><strong>Normality.</strong> The assumption of normality can be checked by a frequency histogram of the residuals or by using a quantile plot where the residuals are plotted against the values expected from a normal distribution. The histogram of residuals should follow a normal distribution. If the points in the quantile plot lie mostly on the line, the residuals are normally distributed. Both of these plots can be obtained from the model object created by the <code>aov</code> function.</p>
<pre class="r"><code>par(mfrow = c(1,2)) # This code put two plots in the same window
hist(Turtles.aov$residuals)
plot(Turtles.aov,which=2)</code></pre>
<p><img src="/statistics/linear-models/anova/anova-single/_index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Violations of normality can be fixed via transformations or by using a different error-distribution in a <a href="/../generalised-linear-models-1/">generalised linear model (GLM)</a>.</p>
<p><strong>Homogeneity of variance.</strong> The assumption of homgeneity of variance, namely that the variation in the residuals is approximately equal across the range of the predictor variable, can be checked by plotting the residuals against the fitted values from the <code>aov</code> model object.</p>
<pre class="r"><code>plot(Turtles.aov,which=1)</code></pre>
<p><img src="/statistics/linear-models/anova/anova-single/_index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Heterogenous variances are indicated by non-random pattern in the residuals vs. fitted plot. Look for an even spread of the residuals on the <em>y</em> axis for each of the levels on the <em>x</em> axis. A fan-shaped distribution with more variance at higher values on the x axis is a common problem when data are skewed. See the testing assumptions of linear models module for more information. If there are strong patterns, one potential solution is to transform the response variable <em>y</em>. If this doesn’t fix the problem the best solution is to use a different error distribution in a <a href="/../generalised-linear-models-1/">generalised linear model (GLM)</a>.</p>
<p><strong>Independence.</strong> ANOVA assumes that all replicate measures are independent of each other (i.e., equally likely to be sampled from the population of possible values for each level). This issue needs to be considered at the design stage. If data are grouped in any way (e.g., half the turtle eggs measured at one time, then the other half measured later), then more complex designs are needed to account for additional factors (e.g., a design with both temperature and time as factors).</p>
<p>There are a variety of measures for dealing with non-independence. These include ensuring all important predictors are in the model; averaging across nested observations; or using a <a href="/../mixed-models-1/">mixed-model</a>.</p>
</div>
<div id="communicating-the-results" class="section level3">
<h3>Communicating the results</h3>
<p><strong>Written.</strong> The results of a one-way ANOVA are usually expressed in text as a short sentence, e.g., “Turtle hatching time differed among the four incubation temperatures (<em>F</em> = 15.98, <em>df</em> = 3,36, <em>p</em> &lt; 0.001)”. A significant effect would be followed by a written description of the post-hoc test results (i.e., exactly which temperatures differed from which). The results from post-hoc tests can also be added to the figure (e.g, by labelling which levels differed).</p>
<p><strong>Visual.</strong> A boxplot or column graph with error bars are suitable for contrasting a continuous variable across levels of categorical variable. See the graphics help for making publication ready versions of these figures.</p>
<pre class="r"><code>boxplot(Days~Temperature, data=Turtles, ylab = &quot;Hatching time (days)&quot;, xlab = &quot;Temperature (°C)&quot;)</code></pre>
<p><img src="/statistics/linear-models/anova/anova-single/_index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="further-help" class="section level3">
<h3>Further help</h3>
<p>Type <code>?aov</code> or <code>?lm</code> to get the R help for these functions.</p>
<p style="margin-left:.5in;text-indent:-.5in">
Quinn and Keough (2002) <em>Experimental design and data analysis for biologists.</em> Cambridge University Press. Ch. 8 Comparing groups or treatments - analysis of variance.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
McKillup (2012) <em>Statistics explained. An introductory guide for life scientists</em> Cambridge University Press. Ch. 11. Single-factor analysis of variance.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Underood, AJ (1997) <em>Experiments in ecology: Their logical design and interpretation using analysis of variance.</em> Cambridge University Press.
</p>
<p><strong>Author</strong>: James Lavender</p>
<p>Last updated:</p>
<pre><code>## [1] &quot;Fri Jan 28 14:45:12 2022&quot;</code></pre>
</div>
