---
weight: 1
title: "One Sample T-test"
output: html_document
aliases: /one-sample-t-test/
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>One of the simplest hypothesis tests in statistics is to test whether a single parameter from a sample of measurements differs from a hypothesised population parameter. The test is asking what is the likelihood of obtaining that sample from a population with certain properties.</p>
<p>For this, we use a one sample <em>t</em>-test. The test statistic, <em>t</em>, has the general form of:</p>
<p><span class="math display">\[t = \frac{St-\theta}{S_{St}}\]</span></p>
<p>where <em>St</em> is the value of the statistic from your sample, <span class="math inline">\(\theta\)</span> is the population value against which you are comparing your sample, and <span class="math inline">\(S_{St}\)</span> is the standard error of your sample statistic.</p>
<p>Such tests can be used for a variety of parameters sampled from populations (e.g., means, slopes and intercepts in linear regression etc.). Here, lets look at a simple example where we test whether the mean of a set of replicated measures differs from a hypothesised value.</p>
<p><img src="One_sample_t_test_image.png" /></p>
<p>Imagine that a forensic scientist was trying to track the origin of some soil samples taken from footprints at a crime scene. She collected 10 samples and analysed the concentration of pollen from a species of pine tree found in a local forest. It was known that soil from that local forest had an average concentration of 125 grains per gram of soil. The one sample <em>t</em>-test will test the likelihood of the ten samples coming from that forest by contrasting the mean concentration in the ten new samples to the value expected if they came from that forest.</p>
<p>The test statistic, <em>t</em> is:</p>
<p><span class="math display">\[t = \frac{\bar{x}-\mu}{SE}\]</span></p>
<p>where <span class="math inline">\(\bar{x}\)</span> is the sample mean, <span class="math inline">\(\mu\)</span> is the population mean and <em>SE</em> is the standard error of the sample.</p>
<p>Note that the size of test statistic depends on two things: 1) how different the sample mean is to the population mean (the numerator) and 2) how much variation is present within the sample (the denominator). The null hypothesis is that the population mean from which the sample was taken is the known value, i.e., <span class="math inline">\(H_o: \mu=125\)</span>.</p>
<div id="running-the-analysis" class="section level3">
<h3>Running the analysis</h3>
<p>The test statistic <em>t</em> is relatively straightforward to manually calculate. The test statistic can then checked against a <em>t</em> distribution in order to determine the probability of obtaining that value of the test statistic if the null hypothesis is true.</p>
<p>To calculate the probability associated with a given value of t in R, use</p>
<pre class="r"><code>pt(q, df = your.df, lower.tail = FALSE) * 2</code></pre>
<p>where <em>q</em> is your value of t, <em>your.df</em> is the degrees of freedom (<em>n</em>-1). The <code>lower.tail = FALSE</code> ensures that you are calculating the probability of getting a <em>t</em> value larger than yours (i.e., the upper tail, P[X &gt; x]). Note that the critical value for <span class="math inline">\(t_{\alpha = 0.05}\)</span> varies depending on the number of degrees of freedom - larger degrees of freedom = smaller critical value of <em>t</em>.</p>
<p>Much easier is to use the <code>t.test</code> function in R to give you the test statistic and its associated probability in one output. For a one sample <em>t</em>-test, we would use:</p>
<pre class="r"><code>t.test(y, mu = your.mu)</code></pre>
<p>where <em>y</em> is a vector with your sample data and <em>your.mu</em> is the population parameter you are comparing the sample to.</p>
<p>For our crime scene example, we could assign our ten measurements to an object called pollen and run the <em>t</em>-test on that object.</p>
<pre class="r"><code>pollen &lt;- c(94, 135, 78, 98, 137, 114, 114, 101, 112, 121)
t.test(pollen, mu = 125)</code></pre>
</div>
<div id="interpreting-the-results" class="section level3">
<h3>Interpreting the results</h3>
<pre><code>## 
##  One Sample t-test
## 
## data:  pollen
## t = -3.0691, df = 9, p-value = 0.01337
## alternative hypothesis: true mean is not equal to 125
## 95 percent confidence interval:
##   97.20685 120.79315
## sample estimates:
## mean of x 
##       109</code></pre>
<p>The output of a one sample <em>t</em>-test is straight-forward to interpret. In the above output, the test statistic <em>t</em> = -3.0691 with 9 degrees of freedom, and a low <em>p</em> value (<em>p</em> = 0.013). We can therefore reject the null hypothesis and conclude that it was unlikely that the soil samples from the crime scene came from the nearby pine forest.</p>
<p>You also get the mean of your sample (109) and the 95% confidence interval for population mean estimated from that sample (this will not overlap your hypothesised mean when the test is significant).</p>
</div>
<div id="assumptions-to-check" class="section level3">
<h3>Assumptions to check</h3>
<p><em>t</em>-tests are parametric tests, which implies we can specify a probability distribution for the population of the variable from which samples were taken. Parametric (and non-parametric) tests have a number of assumptions. If these assumptions are violated we can no longer be sure that the test statistic follows a <em>t</em> distribution, in which case <em>p</em>-values may be inaccurate.</p>
<p><strong>Normality</strong>. The <em>t</em> distribution describes paramaters sampled from a normal population, so assumes that the data are normally distributed. Note however that <em>t tests</em> are reasonably robust to violations of normality (although watch out for the influence of outliers).</p>
<p><strong>Independence</strong>. The observations should have been sampled randomly from a defined population so that sample mean is an unbiased estimate of the population mean. If individual replicates are linked in any way, then the assumption of independence will be violated.</p>
</div>
<div id="communicating-the-results" class="section level3">
<h3>Communicating the results</h3>
<p><strong>Written.</strong> As a minimum, the observed <em>t</em> statistic, the <em>p</em> value and the number of degrees of freedom should be reported. For example, you could write “The mean pollen count from the footprints (109 ) was significantly lower than expected if it was derived from the nearby forest with an average count of 125 (<em>t</em> = 3.07, df = 9, P = 0.01)”.</p>
<p><strong>Visual.</strong> Box plots or frequency histograms can be used to visualise the variation in a single variable. In this example, you might use a line or arrow to indicate the single value (125) that you were comparing the sample to.</p>
<pre class="r"><code>hist(pollen, xlab = &quot;Pollen count&quot;, main = NULL)
abline(v = 125, col = &quot;red&quot;)</code></pre>
<p><img src="/Statistics/t-tests/one-sample-t-test/_index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>boxplot(pollen, xlab = &quot;Pollen count&quot;, horizontal = TRUE)
abline(v = 125, col = &quot;red&quot;)</code></pre>
<p><img src="/Statistics/t-tests/one-sample-t-test/_index_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
</div>
<div id="further-help" class="section level3">
<h3>Further help</h3>
<p>Type <code>?t.test</code> to get the R help for this function.</p>
<p style="margin-left:.5in;text-indent:-.5in">
Quinn and Keough (2002) <em>Experimental design and data analysis for biologists</em>. Cambridge University Press. Chapter 3: Hypothesis testing.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
McKillup (2012) <em>Statistics explained. An introductory guide for life scientists.</em> Cambridge University Press. Chapter 9: Comparing the means of one and two samples of normally distributed data.
</p>
<p><strong>Author</strong>: Alistair Poore</p>
<p><strong>Year:</strong> 2016</p>
<p><strong>Last updated:</strong> Feb 2022</p>
</div>
